import FontAwesome from "react-fontawesome";
import React from "react";

export const ADDPORT:any = <FontAwesome name='fas fa-plus'/>;
export const ADDPORTSELECTED:any =  <FontAwesome name='fas fa-times'/>;
export const INPORT:string = "IN";
export const OUTPORT:string = "OUT";
export const CONSTPORT:string = "*";
export const UNBINARY:string = "unbinary";
export const CONSTANT:string = "constant";
export const MAINPORT:string = "MAINPORT";
export const ADDPRED:string = "P";
export const ADDFUNC:string = "F";
export const BOTH:string = "B";
export const FROM:string = "F";
export const TO:string = "T";
export const PREDICATE:string ="P";
export const FUNCTION:string = "F";
export const BASIC_CURVYNESS:number = 85;
export const UNBINARYNODE:string = "N";
export const CONSTANTNODE:string = "C";
export const TERNARYNODE:string = "T";
export const QUATERNARYNODE:string = "Q";
export const TERNARY = "T";
export const QUATERNARY = "Q";